### ISSUE TITLE
Future maintenance?

### ISSUE THREAD

**Issue by mikeyoon** [fresc81/node-winreg#15]
@fresc81, I noticed that there are some pull requests, one of which is my own, that have been hanging around for a long time. If you are busy or no longer have interest in the project, any chance you can assign another contributor to the project? I'm willing to do it myself if needed.

**Comment by fresc81** [comment]
Thank you for your work and big sorry for letting you guys wait. I have some spare time mid august and will manage this then.

**Comment by justinmchase** [comment]
I emailed @fresc81 earlier today with similar sentiments. It would be really nice to fix a few of these bugs.

**Comment by fresc81** [comment]
Allright I granted both of you access to the GIT repo. I still need to figure out how to grant you access to npm. Thank you guys, I really appreciate your help.

**Comment by justinmchase** [comment]
No thank you for the hard work of getting it started!

The page to add users on npm:
https://docs.npmjs.com/cli/owner

I'm justinmchase there so it would be:
```
npm owner add justinmchase winreg
```

Npm only has two tiers of access, owner or non-owner. Owners show up as "contributors" on the package page, in the order they were added.

**Comment by justinmchase** [comment]
@mikeyoon You can email me if you want to coordinate on this. You probably have a better grasp of the other fixes. My fix appears to be a more narrow fix for my scenario only and is covered by some of the other PR's. If I don't hear from you I will take a look at them and try to apply some fixes myself.

**Comment by fresc81** [comment]
Okay worked. I guess if @mikeyoon needs npm access, you can manage this, too. Right?

**Comment by mikeyoon** [comment]
Cool, thanks @fresc81 for the followup. @justinmchase Sure, email can work, or something like gitter maybe. If email works better for you I can send you one in a bit.

**Comment by justinmchase** [comment]
gitter is fine too.
