### ISSUE TITLE
Cannot write new registry value to HKLM.

### ISSUE THREAD

**Issue by alexandrkazah** [fresc81/node-winreg#16]
I'm trying to write a string value to start up key in HKLM but nothing is written and no errors are shown. Can anyone shine some light on what is happening??? I can do the same to current user HKCU but not the HKLM. Do not know if there is some sort of privileges I need to set or something. 
Here is code for HKCU that works:
var Winreg = require('winreg')
,   regKey = new Winreg({
      hive: Winreg.HKCU,                                          // HKEY_CURRENT_USER
      key:  '\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' // key containing autostart programs
    })
Here is for HKLM that does not work
var Winreg = require('winreg')
,   regKey = new Winreg({
      hive: Winreg.HKLM,                                          // HKEY_LOCAL_MACHINE
      key:  '\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run' // key containing autostart programs
    })

My string value:
regKey.set('RunMyProg', 'REG_SZ', 'Some command ..... here', function () {});

Any help would be much appreciated.
Thanks in advance.

**Comment by fresc81** [comment]
Right click on your windows console icon and select "run as admin". In this console your script should run fine.

**Comment by alexandrkazah** [comment]
Tried it but still nothing happens. Run as admin does not help

**Comment by fresc81** [comment]
I added a section in the README file that hopefully clarifies the most problems that could arise when accessing certain keys, let me know if you still run into problems.
