### ISSUE TITLE
Particular key value is unreadable...

### ISSUE THREAD

**Issue by justinmchase** [fresc81/node-winreg#19]
I cannot read this key with winreg:
```
var VS7 = new WinReg({
	hive: WinReg.HKLM,
	key: '\\' + path.join('SOFTWARE', wowNode, 'Microsoft', 'VisualStudio', 'SxS', 'VS7')
});
VS7.get('12.0', callback); // result is null
```

All of the other values in that key work fine just not that one. I'm assuming it has to do with the fact that it's a number? Or has a `.` perhaps? I don't know what's going wrong, there is no error its just null.

**Comment by justinmchase** [comment]
Also if you do values on they key you get an empty array, even though you can get individual values.

**Comment by justinmchase** [comment]
I have a patch, sending PR (its super simple).

**Comment by fresc81** [comment]
hey @justinmchase didn't you merge this in already? looks good to me, if you tested it lets publish this with next release.

**Comment by justinmchase** [comment]
Yeah one of the other pending PR's actually had this in it already. This can just be closed I think.
