### ISSUE TITLE
Snippet of code that was previously working no longer works with latest update.

### ISSUE THREAD

**Issue by erik33045** [fresc81/node-winreg#26]
After the 0.0.14 update today, a portion of code we were using to get the path of ms build no longer returns any values.  The version specified in our packages.json is version 0.0.11, but there are no other releases available besides 0.0.14.

The snippet that's broken is pasted below:

```javascript
    var regKey = new Winreg({
        hive: Winreg.HKLM,
        key: "\\SOFTWARE\\Microsoft\\MSBuild\\ToolsVersions\\4.0"
    });

    var pathValueName = gulp.isOSWin64() ? "MsBuildToolsPath" : "MsBuildToolsPath32";

    //BROKEN LINE
    regKey.get(pathValueName, function (err, item) {
        if (err) {
            deferred.reject(err);
        }

        var msBuildPath = item.value + 'MSBuild.exe';
```

Is there a place which has previous releases of winreg hosted? Or are we using the function incorrectly?

**Comment by justinmchase** [comment]
If you set your package.json file to `"node-winreg": "0.1.13"` then do an npm update you should get the previous version. We'll try to fix this, sorry about that.

**Comment by erik33045** [comment]
Ah, yeah. Apparently my eyes are failing me. I thought we were specifically targeting one version, but sure enough we were using tilde. Thanks for the response, hope to be able to pull the newest version soon enough!

**Comment by fresc81** [comment]
just updated to version 0.0.15 which should fix your problem
