### ISSUE TITLE
Use semver, release 1.0.0

### ISSUE THREAD

**Issue by feross** [fresc81/node-winreg#30]
Hey there! Great package. Have you thought about releasing version 1.0.0?

See: https://docs.npmjs.com/getting-started/semantic-versioning

> If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule.

It's easier to automatically inherit bugfixes and improvements for free if we can just depend on `^1.0.0` of `winreg`.

**Comment by fresc81** [comment]
I think for releasing 1.0.0 we still need proper docs and tests. What do you mean by easier? Is there a difference how npm handles versions smaller then 1.0?

**Comment by feross** [comment]
Yeah, so npm handles version ranges with the caret `^` prefix by default. For example: `^0.0.16`.

The rules for versions less than `1.0.0` pretty unintuitive, so it's recommended to start at `1.0.0`. That way the rules are simple `^1.0.0` will install anything that's `1.x.x`.

**Comment by feross** [comment]
Also, the npm teams says that if your package has users it should probably already be `1.0.0` :)

Anyway, great work with this.

**Comment by feross** [comment]
Another reason to release 1.0.0 is that it's obvious that there are no breaking changes until you release 2.0.0. Right now, every time you do a point release, users need to look at the commit log because there's no guarantee that 0.0.18 won't break code written assuming 0.0.17.

**Comment by fresc81** [comment]
I guess this is just my way of telling you that this project is not yet ready for production usage. For me a project is ready to be released if its working AND it is documented. At the moment winreg doesn't have proper API docs and the readme file is a mess. But I'm working on it right now. So I hope i can release it as 1.0.0 this evening.

**Comment by fresc81** [comment]
here you go :+1: thank you

**Comment by feross** [comment]
Nice work!
