### ISSUE TITLE
No License file

### ISSUE THREAD

**Issue by jayongg** [fresc81/node-winreg#32]
No license file associated with this project - can you use MIT License? That would help others using/modifying this.

**Comment by jayongg** [comment]
Just saw that it says BSD in the package.json file.  Can you make a LICENSE file so that it's apparent? :)

**Comment by teobugslayer** [comment]
:+1: - it appears that we are not actually allowed to distribute on this module without a license.

**Comment by fresc81** [comment]
the license is BSD Clause 2 like in the [readme file from the test-docs branch](https://github.com/fresc81/node-winreg/blob/tests-docs/README.md). I'll add it for you soon.

**Comment by fresc81** [comment]
allright thats all I can do on my phone :) I'll publish to npm as soon I'm home again

**Comment by jayongg** [comment]
Thank you!

Sent from my Windows Phone
________________________________

**Comment by fresc81** [comment]
npm module is now published, too
