### ISSUE TITLE
Accessing 32-bit registry view

### ISSUE THREAD

**Issue by darkpixel** [fresc81/node-winreg#37]
Is there a way to force accessing a specific registry view?

The REG.EXE command allows the following switches:
```
  /reg:32  Specifies the key should be accessed using the 32-bit registry view.
  /reg:64  Specifies the key should be accessed using the 64-bit registry view.
```

I'm specifically trying to access a key under ```HKLM\Software\Wow6432Node\...```

**Comment by darkpixel** [comment]
Disregard.  I see it in the code, but not in the docs.

Pass {arch: 32} when instantiating the Registry object.

**Comment by fresc81** [comment]
It's not in the Readme, but in the API docs [here](http://fresc81.github.io/node-winreg/Registry.html).
