### ISSUE TITLE
Cannot write to HKCR

### ISSUE THREAD

**Issue by MrBlenny** [fresc81/node-winreg#39]
I am trying to write some keys to HKCR - this does not seem to work:

```
ERROR: Access is denied.
    at mkErrorMsg (app\node_modules\winreg\lib\registry.js:117:12)
    at ChildProcess.<anonymous> (app\node_modules\winreg\lib\registry.js:735:10)
```

Is this expected? Should access to HKCR be restricted for an application NOT running in admin mode (even if the user is an admin)?

**Comment by MrBlenny** [comment]
I suppose this is expected as we should write to `HKCU\\Software\\Classes\`

**Comment by fresc81** [comment]
Yes, write access to HKCR is restricted to elevated processes. So this is what you would expect. But you can always check access to the particular key using REGEDIT. I don't know how the menu item is called in your  language, but there should be a permission setting available in the context menu for each key.
