### ISSUE TITLE
Registry.erase(cb) leaves behind the key (while deleting all the name/value pairs).

### ISSUE THREAD

**Issue by Zren** [fresc81/node-winreg#4]
This is because you use the `/va` argument.

      /va        delete all values under this key.

`Erase` is a good name for this operation, so I'd suggest updating the docs that it doesn't actually delete the key, and make another function that deletes the key and all descendant keys.

Just leave out the `/va` argument for the Registry.delete() function. Eg: https://github.com/Zren/atom-windows-context-menu/blob/master/lib/registry.js#L506

**Comment by spiffytech** [comment]
:+1:
