### ISSUE TITLE
Stubbing Registry method

### ISSUE THREAD

**Issue by Mic75** [fresc81/node-winreg#40]
First of all, thank you for this useful module.

I am currently using it and I would like to stub some Registry instance methods with sinonjs in my tests.
Unfortunatly I can't do it as the Registry's prototype is frozen.

Would you consider unfrozing ? And if not, what approach would you suggest to stub Registry methods ?

**Comment by fresc81** [comment]
Hi @Mic75. As I see sinon.js is currently in the process of being updated to 2.0.0. Did you try installing the latest version of sinonjs using something like
`npm install https://github.com/sinonjs/sinon.git`
Also I cannot really see what's the issue with winreg here. Would you please explain further?

**Comment by Mic75** [comment]
Hi Paul, thanks for your answer.

I am currently using the latest version of sinon, I haven't played with the version 2 yet (which is in pre-release phase), but I don't see it changing how stubs work.

At the end of the registry.js file the Registry constructor function and its prototype are frozen:
```javascript
/* lock Registry class */
Object.freeze(Registry);
Object.freeze(Registry.prototype);
```

I guess that the motivation behind it is to prevent the users of the lib to modify the Registry class at runtime. Problem is that this makes Registry instances instubbable.

Stubbing libraries like Sinon (or Jasmine stubs) modify the object properties at runtime, so they require the object to be mutable, which is prevented by the Object.freeze calls.

**Comment by fresc81** [comment]
Do you need the [RegistryItem](http://fresc81.github.io/node-winreg/RegistryItem.html) class to be unlocked, too?

**Comment by fresc81** [comment]
I'm a bit tired right now. But I can update the module tomorrow.

**Comment by Mic75** [comment]
For consistency sake, I would say that it would be good to have RegistryItem unlocked too. I can do a pull request if you prefer (already forked your repo) ?

**Comment by fresc81** [comment]
I would prefer a solution where you set an environment variable to unlock. Normally you get a performance benefit from locking down objects (don't really know the status here for nodejs). Are you okay with such an solution? You could then just do ` process.env['WINREG_UNLOCK_API'] = '1' ` before requiring winreg within your program. Or set the environment variable prior running your program.

**Comment by fresc81** [comment]
@Mic75 Should be published now.

**Comment by Mic75** [comment]
@fresc81 Great, thank you for the reactivity !
