### ISSUE TITLE
read a key synchronously?

### ISSUE THREAD

**Issue by samkelly** [fresc81/node-winreg#42]
Is this possible?

**Comment by fresc81** [comment]
No, that is not possible, sorry. This module was created when synchonous execution of processes wasn't possible with node. So technically it should now be possible to implement synchronous registry access.

**Comment by alexanderturinske** [comment]
https://github.com/jsolisu/node-winreg/commit/0b85824e5b9745ecba6a459e1d1bcf972d4c392b
