### ISSUE TITLE
Unable to set value for a registry key

### ISSUE THREAD

**Issue by kapilk** [fresc81/node-winreg#8]
Hi,

I am trying to set a Registry key/value in windows 7 (32 Bit). However, I keep getting the error:

[Error: process exited with code 1]

The code I am using is: 

---------------------------------------------------------------------------------------------------------------------
var Winreg = require('winreg');

regKey = new Winreg({
	hive: Winreg.HKLM, 
	key:  '\\System\\CurrentControlSet\\Control\\Session Manager\\Environment' 
});

regKey.set('SOME_KEY', Winreg.REG_SZ, '1', function (err) {
	console.log(err);
});

---------------------------------------------------------------------------------------------------------------------

What am I doing wrong? 

Other methods like regKey.values() and regKey.get() work fine.

Any help would be great. Thanks :)

**Comment by odnarb** [comment]
I too have trouble creating a key then setting it. I've ran the cmd window as admin. I can create via reg.exe just fine.

**Comment by edulan** [comment]
I had the same issue and the problem was that I was trying to remove a key before it even exists. I turned log on to see what was happening and was really helpful. Also I'd recommend you to run the same `REG` query this lib generates to see the output of the command.

**Comment by fresc81** [comment]
I added a section in the README file that hopefully clarifies the most problems that could arise when accessing certain keys, let me know if you still run into problems.
